### ISSUE TITLE
Error:  satisfies the requirement ipfs-http-client==0.7.0a1

### ISSUE THREAD

**Issue by ganeshnic** [JKhan01/blockchain_real_estate_workaround#1]
Error: could not find a version that satisfies the requirement ipfs-http-client==0.7.0a1  any update to resolve it....???

**Comment by JKhan01** [comment]
From what I could figure out is that ipfshttpclient 0.7.0a was a pre release. Probably a beta release not a stable one.
U can just update the package in requirements.txt to 
0.7.0.

When the project was developed pre release was used but not u can use 

- ```
ipfshttpclient==0.7.0
